// <auto-generated />
namespace EF_CodeFirst_demo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedPrice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedPrice));
        
        string IMigrationMetadata.Id
        {
            get { return "202112210748263_addedPrice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
